n = str(input('Escreva seu nome completo: ')).strip()
nome = n.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome {}'.format(nome[0]))
print('Seu ultimo nome {}'.format(nome[len(nome)-1]))